---
- name: ensure glance database is present
  mysql_db:
    name: glance

- name: ensure glance database user is present
  mysql_user:
    name: glance
    host: "{{ item }}"
    password: "{{ glance_db_password }}"
    priv: glance.*:ALL
  with_items:
    - "%"
    - "localhost"
