---
- name: ensure cinder project
  os_project:
    cloud: default
    state: present
    name: openstack
    description: "openstack services"
    domain_id: default
    enabled: true

- name: ensure cinder user
  os_user:
    cloud: default
    state: present
    name: "{{ cinder_os_username }}"
    password: "{{ cinder_os_password }}"
    domain: default
    default_project: openstack

- name: ensure cinder user is admin role
  os_user_role:
    cloud: default
    user: "{{ cinder_os_username }}"
    role: "admin"
    project: "openstack"

- name: ensure cinder v1 service
  os_keystone_service:
    cloud: default
    state: present
    name: cinder
    service_type: volume
    description: "OpenStack Volume Service"

- name: ensure cinder v1 public endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: public
    region: "{{ region_name }}"
    url: "{{ cinder_v1_url }}"

- name: ensure cinder v1 admin endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    region: "{{ region_name }}"
    interface: admin
    url: "{{ cinder_v1_url }}"

- name: ensure cinder v1 internal endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: internal
    region: "{{ region_name }}"
    url: "{{ cinder_v1_url }}"

- name: ensure cinder v2 service
  os_keystone_service:
    cloud: default
    state: present
    name: cinderv2
    service_type: volumev2
    description: "OpenStack Volume Service V2"

- name: ensure cinder v2 internal endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: public
    region: "{{ region_name }}"
    url: "{{ cinder_v2_url }}"

- name: ensure cinder v2 internal endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    region: "{{ region_name }}"
    interface: admin
    url: "{{ cinder_v2_url }}"

- name: ensure cinder v2 internal endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: internal
    region: "{{ region_name }}"
    url: "{{ cinder_v2_url }}"

- name: ensure cinder v3 service
  os_keystone_service:
    cloud: default
    state: present
    name: cinderv3
    service_type: volumev3
    description: "OpenStack Volume Service V3"

- name: ensure cinder v3 public endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: public
    region: "{{ region_name }}"
    url: "{{ cinder_v3_url }}"

- name: ensure cinder v3 admin endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    region: "{{ region_name }}"
    interface: admin
    url: "{{ cinder_v3_url }}"

- name: ensure cinder v3 internal endpoint
  os_keystone_endpoint:
    cloud: default
    service: cinder
    interface: internal
    region: "{{ region_name }}"
    url: "{{ cinder_v3_url }}"
