---
- name: ensure cinder database is present
  mysql_db:
    name: cinder

- name: ensure cinder database user is present
  mysql_user:
    name: cinder
    host: "{{ item }}"
    password: "{{ cinder_db_password }}"
    priv: cinder.*:ALL
  with_items:
    - "%"
    - "localhost"

- name: ensure database is synchronized
  command: "cinder-manage db sync"
  become: yes
  become_user: cinder
  changed_when: false
