#!/bin/bash

# Sanitize language settings to avoid commands bailing out
# with "unsupported locale setting" errors.
unset LANG
unset LANGUAGE
LC_ALL=C
export LC_ALL

# Make sure umask is sane
umask 022

## source functions
topdir=$(cd $(dirname $0) && pwd)

USE_DIY_YUM_REPOS=false
if [ -f "${topdir}/fermentrc" ]; then
    source ${topdir}/fermentrc
fi
source "${topdir}/services/common"

ALL_COMMANDS=('install' 'config' 'start' 'stop' 'restart' 'remove' 'reinstall')
ALL_SERVICES=($(ls -F "${topdir}/services"))


usage() {
    echo "usage: $0 <command> <service>"
    echo "<command>: [${ALL_COMMANDS[@]/%/,}]"
    echo "<service>: [${ALL_SERVICES[@]/%/,}]"
    exit
}

is_valid_command() {
    local command=$1
    for val in ${ALL_COMMANDS[@]}; do
        if [[ "${val}" == "${command}" ]]; then
            return 0
        fi
    done
    return 1
}

is_valid_service() {
    local service=$1
    for val in ${ALL_SERVICES[@]}; do
        if [[ "${val}" == "${service}" ]]; then
            return 0
        fi
    done
    return 1
}

init_repository() {
    local reposdir=$1

}

## check parameters
if [[ $# -ne 2 ]]; then
    usage
fi

command=$1
service=$2

is_valid_command ${command} || usage
is_valid_service ${service} || usage

## check necessary parameters
if [[ -z "${SERVICE_HOST}" || -z "${HOST_ADDRESS}" ]]; then
    echo "environment variable 'SERVICE_HOST' and 'HOST_ADDRESS' can not be null"
    echo "set those two environment variable and run this scirpt again."
    exit
fi
if [ -z "$REPOSERVER" -a "$USE_DIY_YUM_REPOS" = true ]; then
    echo "you must set 'REPOSERVER' if you want to use your own repository"
    exit
fi

## init yum repository
if [ "$USE_DIY_YUM_REPOS" = true ]; then
    reposdir=${reposdir:-/tmp/ferment}
    yum_conf=${reposdir}/yum.conf
    repo_conf=${reposdir}/openstack.repo

    # generate yum config file
    mkdir -p ${reposdir}
    cat > ${yum_conf} << EOF
[main]
keepcache=0
debuglevel=2
exactarch=1
obsoletes=1
plugins=0
gpgcheck=0
installonly_limit=5
reposdir=${reposdir}
cachedir=${reposdir}
logfile=${reposdir}/yum.log
EOF

    cat > ${repo_conf} << EOF
[openstack]
name=OpenStack packages
baseurl=http://${REPOSERVER}/centos/\$releasever/\$basearch
enabled=1
gpgcheck=0
EOF

    export YUM="yum -c ${yum_conf}"
else
    export YUM="yum"
fi

source "${topdir}/services/${service}"

## execute functions
if [[ "install" == "${command}" ]]; then
    eval "install_${service}"
    eval "configure_${service}"
    eval "init_${service}"
elif [[ "config" == "${command}" ]]; then
    eval "configure_${service}"
elif [[ "start" == "${command}" ]]; then
    eval "start_${service}"
elif [[ "stop" == "${command}" ]]; then
    eval "stop_${service}"
elif [[ "restart" == "${command}" ]]; then
    eval "stop_${service}"
    eval "start_${service}"
elif [[ "remove" == "${command}" ]]; then
    eval "stop_${service}"
    eval "cleanup_${service}"
elif [[ "reinstall" == "${command}" ]]; then
    eval "stop_${service}"
    eval "cleanup_${service}"
    eval "install_${service}"
    eval "configure_${service}"
    eval "init_${service}"
else
    usage
fi
