---
# This playbook install and config rabbitmq server.

- name: Install rabbitmq server
  yum: name={{ item }} state=present
  with_items:
    - erlang
    - rabbitmq-server

- name: Generate main configure
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
  notify: restart rabbitmq

- name: Start rabbitmq on boot
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create admin user for openstack services
  rabbitmq_user:
    user: openstack
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
