---
# This playbook install and config rabbitmq server.

- name: Install rabbitmq server
  yum: name={{ item }} state=present
  with_items:
    - erlang
    - rabbitmq-server

- name: Generate main configure
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
  notify: restart rabbitmq

- name: Start rabbitmq on boot
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
