---
- name: ensure neutron database is present
  mysql_db:
    name: neutron

- name: ensure neutron database user is present
  mysql_user:
    name: neutron
    host: "{{ item }}"
    password: "{{ neutron_db_password }}"
    priv: neutron.*:ALL
  with_items:
    - "%"
    - "localhost"

- name: ensure database is synchronized
  command: >
    neutron-db-manage
    --config-file /etc/neutron/neutron.conf
    --config-file /etc/neutron/plugin.ini
    upgrade head
  become: yes
  become_user: neutron
  changed_when: false
