---
- name: ensure neutron server start on boot
  service:
    name: neutron-server
    state: started
    enabled: yes

- name: ensure neutron openvswitch agent start on boot
  service:
    name: neutron-openvswitch-agent
    state: started
    enabled: yes

- name: ensure neutron dhcp agent start on boot
  service:
    name: neutron-dhcp-agent
    state: started
    enabled: yes

- name: ensure neutron l3 agent start on boot
  service:
    name: neutron-l3-agent
    state: started
    enabled: yes

- name: ensure neutron metadata agent start on boot
  service:
    name: neutron-metadata-agent
    state: started
    enabled: yes
