---
- name: ensure nova database is present
  mysql_db:
    name: nova
  mysql_db:
    name: nova_api

- name: ensure nova database user is present
  mysql_user:
    name: nova
    host: "{{ item }}"
    password: "{{ nova_db_password }}"
    priv: nova.*:ALL/nova_api.*:ALL
  with_items:
    - "%"
    - "localhost"

- name: ensure database is synchronized
  command: nova-manage --config-file /etc/nova/nova.conf db sync
  become: yes
  become_user: nova
  changed_when: false
